/*


Creacion de tablas de rcarrero.paises, el nombre de la tabla debe ser en singular

Se llamara rcarrero.pais, tendra codigo, nombre

NOMBRE, CODIGO, rcarrero.pais

*/

/*
CREATE TABLE pais(
    codigo number primary key, 
    nombre VARCHAR2(100));
*/



BEGIN
INSERT INTO rcarrero.pais VALUES (2,'ALBANIA');
INSERT INTO rcarrero.pais VALUES (3,'ALEMANIA');
INSERT INTO rcarrero.pais VALUES (4,'ANDORRA');
INSERT INTO rcarrero.pais VALUES (5,'ANGOLA');
INSERT INTO rcarrero.pais VALUES (6,'ANTIGUA Y BARBUDA');
INSERT INTO rcarrero.pais VALUES (7,'ARABIA SAUDITA');
INSERT INTO rcarrero.pais VALUES (8,'ARGELIA');
INSERT INTO rcarrero.pais VALUES (9,'ARGENTINA');
INSERT INTO rcarrero.pais VALUES (10,'ARMENIA');
INSERT INTO rcarrero.pais VALUES (11,'AUSTRALIA');
INSERT INTO rcarrero.pais VALUES (12,'AUSTRIA');
INSERT INTO rcarrero.pais VALUES (13,'AZERBAIYÁN');
INSERT INTO rcarrero.pais VALUES (14,'BAHAMAS');
INSERT INTO rcarrero.pais VALUES (15,'BANGLADÉS');
INSERT INTO rcarrero.pais VALUES (16,'BARBADOS');
INSERT INTO rcarrero.pais VALUES (17,'BARÉIN');
INSERT INTO rcarrero.pais VALUES (18,'BÉLGICA');
INSERT INTO rcarrero.pais VALUES (19,'BELICE');
INSERT INTO rcarrero.pais VALUES (20,'BENIN');
INSERT INTO rcarrero.pais VALUES (21,'BIELORRUSIA');
INSERT INTO rcarrero.pais VALUES (22,'BOLIVIA');
INSERT INTO rcarrero.pais VALUES (23,'BOSNIA Y HERZEGOVINA');
INSERT INTO rcarrero.pais VALUES (24,'BOTSUANA');
INSERT INTO rcarrero.pais VALUES (25,'BRASIL');
INSERT INTO rcarrero.pais VALUES (26,'BRUNEI');
INSERT INTO rcarrero.pais VALUES (27,'BULGARIA');
INSERT INTO rcarrero.pais VALUES (28,'BURKINA FASO');
INSERT INTO rcarrero.pais VALUES (29,'BURUNDI');
INSERT INTO rcarrero.pais VALUES (30,'BUTÁN');
INSERT INTO rcarrero.pais VALUES (31,'CABO VERDE');
INSERT INTO rcarrero.pais VALUES (32,'CAMBOYA');
INSERT INTO rcarrero.pais VALUES (33,'CAMERÚN');
INSERT INTO rcarrero.pais VALUES (34,'CANADÁ');
INSERT INTO rcarrero.pais VALUES (35,'CATAR');
INSERT INTO rcarrero.pais VALUES (36,'CHAD');
INSERT INTO rcarrero.pais VALUES (37,'CHILE');
INSERT INTO rcarrero.pais VALUES (38,'CHINA');
INSERT INTO rcarrero.pais VALUES (39,'CHIPRE');
INSERT INTO rcarrero.pais VALUES (40,'COLOMBIA');
INSERT INTO rcarrero.pais VALUES (41,'COMORAS');
INSERT INTO rcarrero.pais VALUES (42,'COREA DEL NORTE');
INSERT INTO rcarrero.pais VALUES (43,'COREA DEL SUR');
INSERT INTO rcarrero.pais VALUES (44,'COSTA DE MARFIL');
INSERT INTO rcarrero.pais VALUES (45,'COSTA RICA');
INSERT INTO rcarrero.pais VALUES (46,'CROACIA');
INSERT INTO rcarrero.pais VALUES (47,'CUBA');
INSERT INTO rcarrero.pais VALUES (48,'DINAMARCA');
INSERT INTO rcarrero.pais VALUES (49,'DOMINICA');
INSERT INTO rcarrero.pais VALUES (50,'ECUADOR');
INSERT INTO rcarrero.pais VALUES (51,'EGIPTO');
INSERT INTO rcarrero.pais VALUES (52,'EL SALVADOR');
INSERT INTO rcarrero.pais VALUES (53,'EMIRATOS ARABES UNIDOS');
INSERT INTO rcarrero.pais VALUES (54,'ERITREA');
INSERT INTO rcarrero.pais VALUES (55,'ESLOVAQUIA');
INSERT INTO rcarrero.pais VALUES (56,'ESLOVENIA');
INSERT INTO rcarrero.pais VALUES (57,'ESPAÑA');
INSERT INTO rcarrero.pais VALUES (58,'ESTADOS UNIDOS');
INSERT INTO rcarrero.pais VALUES (59,'ESTONIA');
INSERT INTO rcarrero.pais VALUES (60,'ETIOPÍA');
INSERT INTO rcarrero.pais VALUES (61,'FILIPINAS');
INSERT INTO rcarrero.pais VALUES (62,'FINLANDIA');
INSERT INTO rcarrero.pais VALUES (63,'FIYI');
INSERT INTO rcarrero.pais VALUES (64,'FRANCIA');
INSERT INTO rcarrero.pais VALUES (65,'GABÓN');
INSERT INTO rcarrero.pais VALUES (66,'GAMBIA');
INSERT INTO rcarrero.pais VALUES (67,'GEORGIA');
INSERT INTO rcarrero.pais VALUES (68,'GHANA');
INSERT INTO rcarrero.pais VALUES (69,'GRANADA');
INSERT INTO rcarrero.pais VALUES (70,'GRECIA');
INSERT INTO rcarrero.pais VALUES (71,'GUATEMALA');
INSERT INTO rcarrero.pais VALUES (72,'GUINEA');
INSERT INTO rcarrero.pais VALUES (73,'GUINEA ECUATORIAL');
INSERT INTO rcarrero.pais VALUES (74,'GUINEA-BISSAU');
INSERT INTO rcarrero.pais VALUES (75,'GUYANA');
INSERT INTO rcarrero.pais VALUES (76,'HAITÍ');
INSERT INTO rcarrero.pais VALUES (77,'HONDURAS');
INSERT INTO rcarrero.pais VALUES (78,'HUNGRÍA');
INSERT INTO rcarrero.pais VALUES (79,'INDIA');
INSERT INTO rcarrero.pais VALUES (80,'INDONESIA');
INSERT INTO rcarrero.pais VALUES (81,'IRÁN');
INSERT INTO rcarrero.pais VALUES (82,'IRAQ');
INSERT INTO rcarrero.pais VALUES (83,'IRLANDA');
INSERT INTO rcarrero.pais VALUES (84,'ISLANDIA');
INSERT INTO rcarrero.pais VALUES (85,'ISLAS MARSHALL');
INSERT INTO rcarrero.pais VALUES (86,'ISLAS SALOMÓN');
INSERT INTO rcarrero.pais VALUES (87,'ISRAEL');
INSERT INTO rcarrero.pais VALUES (88,'ITALIA');
INSERT INTO rcarrero.pais VALUES (89,'JAMAICA');
INSERT INTO rcarrero.pais VALUES (90,'JAPÓN');
INSERT INTO rcarrero.pais VALUES (91,'JORDANIA');
INSERT INTO rcarrero.pais VALUES (92,'KAZAJISTÁN');
INSERT INTO rcarrero.pais VALUES (93,'KENIA');
INSERT INTO rcarrero.pais VALUES (94,'KIRGUISTÁN');
INSERT INTO rcarrero.pais VALUES (95,'KIRIBATI');
INSERT INTO rcarrero.pais VALUES (96,'KUWAIT');
INSERT INTO rcarrero.pais VALUES (97,'LAOS');
INSERT INTO rcarrero.pais VALUES (98,'LESOTO');
INSERT INTO rcarrero.pais VALUES (99,'LETONIA');
INSERT INTO rcarrero.pais VALUES (100,'LÍBANO');
INSERT INTO rcarrero.pais VALUES (101,'LIBERIA');
INSERT INTO rcarrero.pais VALUES (102,'LIBIA');
INSERT INTO rcarrero.pais VALUES (103,'LIECHTENSTEIN');
INSERT INTO rcarrero.pais VALUES (104,'LITUANIA');
INSERT INTO rcarrero.pais VALUES (105,'LUXEMBURGO');
INSERT INTO rcarrero.pais VALUES (106,'MADAGASCAR');
INSERT INTO rcarrero.pais VALUES (107,'MALASIA');
INSERT INTO rcarrero.pais VALUES (108,'MALAUI');
INSERT INTO rcarrero.pais VALUES (109,'MALDIVAS');
INSERT INTO rcarrero.pais VALUES (110,'MALI');
INSERT INTO rcarrero.pais VALUES (111,'MALTA');
INSERT INTO rcarrero.pais VALUES (112,'MARRUECOS');
INSERT INTO rcarrero.pais VALUES (113,'MAURICIO');
INSERT INTO rcarrero.pais VALUES (114,'MAURITANIA');
INSERT INTO rcarrero.pais VALUES (115,'MÉXICO');
INSERT INTO rcarrero.pais VALUES (116,'MICRONESIA');
INSERT INTO rcarrero.pais VALUES (117,'MOLDAVIA');
INSERT INTO rcarrero.pais VALUES (118,'MÓNACO');
INSERT INTO rcarrero.pais VALUES (119,'MONGOLIA');
INSERT INTO rcarrero.pais VALUES (120,'MONTENEGRO');
INSERT INTO rcarrero.pais VALUES (121,'MOZAMBIQUE');
INSERT INTO rcarrero.pais VALUES (122,'MYANMAR (BIRMANIA)');
INSERT INTO rcarrero.pais VALUES (123,'NAMIBIA');
INSERT INTO rcarrero.pais VALUES (124,'NAURU');
INSERT INTO rcarrero.pais VALUES (125,'NEPAL');
INSERT INTO rcarrero.pais VALUES (126,'NICARAGUA');
INSERT INTO rcarrero.pais VALUES (127,'NÍGER');
INSERT INTO rcarrero.pais VALUES (128,'NIGERIA');
INSERT INTO rcarrero.pais VALUES (129,'NORUEGA');
INSERT INTO rcarrero.pais VALUES (130,'NUEVA ZELANDA');
INSERT INTO rcarrero.pais VALUES (131,'OMÁN');
INSERT INTO rcarrero.pais VALUES (132,'PAÍSES BAJOS');
INSERT INTO rcarrero.pais VALUES (133,'PAKISTÁN');
INSERT INTO rcarrero.pais VALUES (134,'PALAOS');
INSERT INTO rcarrero.pais VALUES (135,'PALESTINA');
INSERT INTO rcarrero.pais VALUES (136,'PANAMÁ');
INSERT INTO rcarrero.pais VALUES (137,'PAPÚA NUEVA GUINEA');
INSERT INTO rcarrero.pais VALUES (138,'PARAGUAY');
INSERT INTO rcarrero.pais VALUES (139,'PERÚ');
INSERT INTO rcarrero.pais VALUES (140,'POLONIA');
INSERT INTO rcarrero.pais VALUES (141,'PORTUGAL');
INSERT INTO rcarrero.pais VALUES (142,'PUERTO RICO');
INSERT INTO rcarrero.pais VALUES (143,'REINO UNIDO');
INSERT INTO rcarrero.pais VALUES (144,'REPÚBLICA CENTROAFRICANA');
INSERT INTO rcarrero.pais VALUES (145,'REPÚBLICA CHECA');
INSERT INTO rcarrero.pais VALUES (146,'REPÚBLICA DE MACEDONIA');
INSERT INTO rcarrero.pais VALUES (147,'REPÚBLICA DEL CONGO');
INSERT INTO rcarrero.pais VALUES (148,'REPÚBLICA DEMOCRÁTICA DEL CONGO');
INSERT INTO rcarrero.pais VALUES (149,'REPÚBLICA DOMINICANA');
INSERT INTO rcarrero.pais VALUES (150,'REPÚBLICA SAHARAUI');
INSERT INTO rcarrero.pais VALUES (151,'RUANDA');
INSERT INTO rcarrero.pais VALUES (152,'RUMANIA');
INSERT INTO rcarrero.pais VALUES (153,'RUSIA');
INSERT INTO rcarrero.pais VALUES (154,'SAMOA');
INSERT INTO rcarrero.pais VALUES (155,'SAN CRISTÓBAL Y NIEVES');
INSERT INTO rcarrero.pais VALUES (156,'SAN MARINO');
INSERT INTO rcarrero.pais VALUES (157,'SAN VICENTE Y LAS GRANADINAS');
INSERT INTO rcarrero.pais VALUES (158,'SANTA LUCÍA');
INSERT INTO rcarrero.pais VALUES (159,'SANTO TOMÉ Y PRÍNCIPE');
INSERT INTO rcarrero.pais VALUES (160,'SENEGAL');
INSERT INTO rcarrero.pais VALUES (161,'SERBIA');
INSERT INTO rcarrero.pais VALUES (162,'SEYCHELLES');
INSERT INTO rcarrero.pais VALUES (163,'SIERRA LEONA');
INSERT INTO rcarrero.pais VALUES (164,'SINGAPUR');
INSERT INTO rcarrero.pais VALUES (165,'SIRIA');
INSERT INTO rcarrero.pais VALUES (166,'SOMALIA');
INSERT INTO rcarrero.pais VALUES (167,'SRI LANKA');
INSERT INTO rcarrero.pais VALUES (168,'SUAZILANDIA');
INSERT INTO rcarrero.pais VALUES (169,'SUDÁFRICA');
INSERT INTO rcarrero.pais VALUES (170,'SUDÁN DEL NORTE');
INSERT INTO rcarrero.pais VALUES (171,'SUDÁN DEL SUR');
INSERT INTO rcarrero.pais VALUES (172,'SUECIA');
INSERT INTO rcarrero.pais VALUES (173,'SUIZA');
INSERT INTO rcarrero.pais VALUES (174,'SURINAM');
INSERT INTO rcarrero.pais VALUES (175,'TAILANDIA');
INSERT INTO rcarrero.pais VALUES (176,'TAIWAN');
INSERT INTO rcarrero.pais VALUES (177,'TANZANIA');
INSERT INTO rcarrero.pais VALUES (178,'TAYIKISTÁN');
INSERT INTO rcarrero.pais VALUES (179,'TIMOR ORIENTAL');
INSERT INTO rcarrero.pais VALUES (180,'TOGO');
INSERT INTO rcarrero.pais VALUES (181,'TONGA');
INSERT INTO rcarrero.pais VALUES (182,'TRINIDAD Y TOBAGO');
INSERT INTO rcarrero.pais VALUES (183,'TÚNEZ');
INSERT INTO rcarrero.pais VALUES (184,'TURKMENISTÁN');
INSERT INTO rcarrero.pais VALUES (185,'TURQUÍA');
INSERT INTO rcarrero.pais VALUES (186,'TUVALU');
INSERT INTO rcarrero.pais VALUES (187,'UCRANIA');
INSERT INTO rcarrero.pais VALUES (188,'UGANDA');
INSERT INTO rcarrero.pais VALUES (189,'URUGUAY');
INSERT INTO rcarrero.pais VALUES (190,'UZBEKISTÁN');
INSERT INTO rcarrero.pais VALUES (191,'VANUATU');
INSERT INTO rcarrero.pais VALUES (192,'VATICANO');
INSERT INTO rcarrero.pais VALUES (193,'VENEZUELA');
INSERT INTO rcarrero.pais VALUES (194,'VIETNAM');
INSERT INTO rcarrero.pais VALUES (195,'YEMEN');
INSERT INTO rcarrero.pais VALUES (196,'YIBUTI');
INSERT INTO rcarrero.pais VALUES (197,'ZAMBIA');
INSERT INTO rcarrero.pais VALUES (198,'ZIMBABUE');

END;
/

SELECT * FROM PAIS;